create rack app
Avanera/rack-app pull request #1
Opened 2020-05-24 11:59 UTC by Avanera

2020-05-24 12:10 UTC, BubuntuClu requested changes

2020-05-24 12:10 UTC, BubuntuClu commented on time_handler.rb
> +    call(params['format'].split(','))
call надо вызывать в месте где инициализировала объект. в методе инициализации это делать не надо.

2020-05-24 12:10 UTC, BubuntuClu commented on app.rb
> +    time = TimeHandler.new(request.params)
создавать объект есть смысл только когда все условия подходят. зачем создавать этот объект если страница другая запрошена?

2020-05-24 12:10 UTC, BubuntuClu commented on app.rb
> +    if time.unknown.empty?
стоит сделать метод `valid?` который проверит это условие

2020-05-24 12:10 UTC, BubuntuClu commented on app.rb
> +      response(200, Time.now.strftime(time.valid))
тут тоже стоит сделать метод в твоем классе, который вернет нужные данные

2020-05-24 12:10 UTC, BubuntuClu commented on time_handler.rb
> +    call(params['format'].split(','))
вспомни как был сделан сервис по работе с октокитом

2020-05-24 12:10 UTC, BubuntuClu commented on app.rb
> +    [
Rack::Response можно использовать

2020-05-24 12:45 UTC, Avanera commented on time_handler.rb
> +    call(params['format'].split(','))
сделала вызов `time.call(request.params['format'].split(','))`  из класса App

2020-05-24 12:45 UTC, Avanera commented on app.rb
> +    time = TimeHandler.new(request.params)
перенесла проверку `if path != '/time'` выше

2020-05-24 12:54 UTC, Avanera commented on app.rb
> +    if time.unknown.empty?
сделала

2020-05-24 12:57 UTC, Avanera commented on app.rb
> +      response(200, Time.now.strftime(time.valid))
сделала formatted

2020-05-25 05:57 UTC, Avanera commented on app.rb
> +    [
сделала с Rack::Response

2020-05-25 07:47 UTC, BubuntuClu requested changes

2020-05-25 07:47 UTC, BubuntuClu commented on app.rb
> +    @response = Rack::Response.new
@request и @response не надо делать инстанс переменной. прокинь @request явно в метод.
@response вообще должен создаваться только в методе отправке

2020-05-25 07:47 UTC, BubuntuClu commented on app.rb
> +    return not_found_response if @request.path != '/time'
not_found_response/no_format_response/perform_format_response. это все один метод. отличается только код и текст. передавай код и текст в метод

2020-05-25 07:47 UTC, BubuntuClu commented on app.rb
> +    if @time.valid?
это не метод отправки должен определять. метод отправки только статус и текст подставляет и отправлет

2020-05-25 07:47 UTC, BubuntuClu commented on app.rb
> +    @time.call(@request.params['format'].split(','))
тут не надо ничего передавать. ты уже передела эти параметры в инициализации

2020-05-25 07:47 UTC, BubuntuClu commented on time_handler.rb
> +    @valid_format = ''
параметры еще надо куда-то запихнуть, а то они передаются, но не используются

2020-05-25 07:47 UTC, BubuntuClu commented on log/app.log
> +I, [2020-05-25T12:58:16.819592 #1251]  INFO -- : {"GATEWAY_INTERFACE"=>"CGI/1.1", "PATH_INFO"=>"/time", "QUERY_STRING"=>"format=month,year", "REMOTE_ADDR"=>"::1", "REMOTE_HOST"=>"::1", "REQUEST_METHO
в гитигнор

2020-05-25 07:47 UTC, BubuntuClu commented on app.rb
> +      @response.write "Unknown time format #{@time.unknown_format}"
а если несколько неверных форматов будет? для получения этой строки сделать метод бы в классе твоем

2020-05-25 08:39 UTC, Avanera commented on app.rb
> +    if @time.valid?
ок

2020-05-25 08:39 UTC, Avanera commented on app.rb
> +    return not_found_response if @request.path != '/time'
ок

2020-05-25 08:42 UTC, Avanera commented on app.rb
> +    @time.call(@request.params['format'].split(','))
ок

2020-05-25 08:42 UTC, Avanera commented on time_handler.rb
> +    @valid_format = ''
ок

2020-05-25 09:12 UTC, Avanera commented on log/app.log
> +I, [2020-05-25T12:58:16.819592 #1251]  INFO -- : {"GATEWAY_INTERFACE"=>"CGI/1.1", "PATH_INFO"=>"/time", "QUERY_STRING"=>"format=month,year", "REMOTE_ADDR"=>"::1", "REMOTE_HOST"=>"::1", "REQUEST_METHO
ок

2020-05-25 09:15 UTC, Avanera commented on app.rb
> +      @response.write "Unknown time format #{@time.unknown_format}"
@time.unknown_format - это массив со всеми неверными форматами. значит не нужно делать еще один метод?

2020-05-25 12:10 UTC, Avanera commented on app.rb
> +    @response = Rack::Response.new
ок

2020-05-25 13:42 UTC, BubuntuClu commented on app.rb
> +      @response.write "Unknown time format #{@time.unknown_format}"
нужен. как у тебя массив в строку будет переведен, смотрела? убираешь ридер, делаешь метод, который возвращает строку неверных форматов и сюда подставляет

2020-05-25 16:16 UTC, Avanera commented on app.rb
> +      @response.write "Unknown time format #{@time.unknown_format}"
ok

2020-05-25 16:18 UTC, merged